name: OpenUptimes Ping Check

on:
  push:
    branches:
      - '**'  # Run on any branch
  schedule:
    # Default to run every 5 minutes, but this should be configured in the app
    - cron: '*/5 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  ping:
    name: Ping Service Check
    runs-on: ubuntu-latest
    steps:
      - name: Perform Ping
        env:
          PING_API_KEY: ${{ secrets.PING_API_KEY }}
          RUN_ID: ${{ github.run_id }}
          APP_URL: ${{ vars.APP_URL || 'http://localhost:3000' }}
        run: |
          echo "Running ping check (ID: $RUN_ID)"
          
          # Construct the API URL
          PING_URL="${APP_URL}/api/ping?runId=${RUN_ID}"
          
          # Make the request with curl
          HTTP_STATUS=$(curl -s -o response.txt -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-Ping-Scheduler" \
            -H "X-API-Key: $PING_API_KEY" \
            "$PING_URL")
          
          # Check if successful
          if [ $HTTP_STATUS -ne 200 ]; then
            echo "Error: Received HTTP status $HTTP_STATUS"
            cat response.txt
            exit 1
          fi
          
          echo "Ping successful"
          cat response.txt 